### ISSUE TITLE
Archgw should not panic when....

### ISSUE THREAD

**Issue by salmanap** [katanemo/arch#243]
The model_server doesn't boot up properly

**Comment by salmanap** [comment]
`[2024-11-01 07:34:30.843][150][debug][wasm] [source/extensions/common/wasm/context.cc:1192] wasm log prompt_gateway: starting up arch filter in mode: prompt gateway mode               
[2024-11-01 07:34:30.846][135][debug][wasm] [source/extensions/common/wasm/context.cc:1192] wasm log prompt_gateway: starting up arch filter in mode: prompt gateway mode               
[2024-11-01 07:34:30.846][143][debug][wasm] [source/extensions/common/wasm/context.cc:1192] wasm log prompt_gateway: starting up arch filter in mode: prompt gateway mode               
[2024-11-01 07:34:30.846][138][debug][wasm] [source/extensions/common/wasm/context.cc:1192] wasm log prompt_gateway: starting up arch filter in mode: prompt gateway mode               
[2024-11-01 07:34:30.847][148][debug][wasm] [source/extensions/common/wasm/context.cc:1192] wasm log prompt_gateway: starting up arch filter in mode: prompt gateway mode               
[2024-11-01 07:34:30.851][156][debug][wasm] [source/extensions/common/wasm/context.cc:1192] wasm log prompt_gateway: starting up arch filter in mode: prompt gateway mode               
[2024-11-01 07:34:30.907][158][debug][wasm] [source/extensions/common/wasm/context.cc:1192] wasm log prompt_gateway: starting up arch filter in mode: prompt gateway mode               
[2024-11-01 07:34:35.602][9][debug][wasm] [source/extensions/common/wasm/context.cc:1192] wasm log prompt_gateway: filter_context: on_http_call_response called with token_id: 4        
[2024-11-01 07:34:35.602][57][debug][wasm] [source/extensions/common/wasm/context.cc:1192] wasm log prompt_gateway: filter_context: on_http_call_response called with token_id: 8       
[2024-11-01 07:34:35.602][9][critical][wasm] [source/extensions/common/wasm/context.cc:1204] wasm log prompt_gateway: panicked at prompt_gateway/src/filter_context.rs:148:25:          
Error deserializing embedding response. body: "upstream connect error or disconnect/reset before headers. reset reason: connection timeout": Error("expected value", line: 1, column: 1)
[2024-11-01 07:34:35.602][141][debug][wasm] [source/extensions/common/wasm/context.cc:1192] wasm log prompt_gateway: filter_context: on_http_call_response called with token_id: 8      
[2024-11-01 07:34:35.602][57][critical][wasm] [source/extensions/common/wasm/context.cc:1204] wasm log prompt_gateway: panicked at prompt_gateway/src/filter_context.rs:148:25:         
Error deserializing embedding response. body: "upstream connect error or disconnect/reset before headers. reset reason: connection timeout": Error("expected value", line: 1, column: 1)
[2024-11-01 07:34:35.602][141][critical][wasm] [source/extensions/common/wasm/context.cc:1204] wasm log prompt_gateway: panicked at prompt_gateway/src/filter_context.rs:148:25:        
Error deserializing embedding response. body: "upstream connect error or disconnect/reset before headers. reset reason: connection timeout": Error("expected value", line: 1, column: 1)
[2024-11-01 07:34:35.603][9][error][wasm] [source/extensions/common/wasm/wasm_vm.cc:38] Function: proxy_on_http_call_response failed: Uncaught RuntimeError: unreachable                
Proxy-Wasm plugin in-VM backtrace:                                                                                                                                                      
  0:  0xd23a1 - __rust_start_panic                                                                                                                                                      
  1:  0xd2266 - rust_panic                                                                                                                                                              
  2:  0xd201c - std::panicking::rust_panic_with_hook::h50e657195af0239c                                                                                                                 
  3:  0xd1363 - std::panicking::begin_panic_handler::_$u7b$$u7b$closure$u7d$$u7d$::h0187e6969a85aab0                                                                                    
  4:  0xd12ca - std::sys_common::backtrace::__rust_end_short_backtrace::h575fb82445d56667                                                                                               
  5:  0xd1bb4 - rust_begin_unwind                                                                                                                                                       
  6:  0xd743f - core::panicking::panic_fmt::ha6764f2272b7fb95                                                                                                                           
  7:  0x7e0ba - _$LT$prompt_gateway..filter_context..FilterContext$u20$as$u20$proxy_wasm..traits..Context$GT$::on_http_call_response::hb27b0eacd5787919                                 
  8:  0xc5d4a - proxy_wasm::dispatcher::Dispatcher::on_http_call_response::h010c524b3251d0a7                                                                                            
  9:  0xcacd6 - proxy_on_http_call_response                                                                                                         `

**Comment by salmanap** [comment]
[2024-11-01 07:34:30.843][150][debug][wasm] [source/extensions/common/wasm/context.cc:1192] wasm log prompt_gateway: starting up arch filter in mode: prompt gateway mode               
[2024-11-01 07:34:30.846][135][debug][wasm] [source/extensions/common/wasm/context.cc:1192] wasm log prompt_gateway: starting up arch filter in mode: prompt gateway mode               
[2024-11-01 07:34:30.846][143][debug][wasm] [source/extensions/common/wasm/context.cc:1192] wasm log prompt_gateway: starting up arch filter in mode: prompt gateway mode               
[2024-11-01 07:34:30.846][138][debug][wasm] [source/extensions/common/wasm/context.cc:1192] wasm log prompt_gateway: starting up arch filter in mode: prompt gateway mode               
[2024-11-01 07:34:30.847][148][debug][wasm] [source/extensions/common/wasm/context.cc:1192] wasm log prompt_gateway: starting up arch filter in mode: prompt gateway mode               
[2024-11-01 07:34:30.851][156][debug][wasm] [source/extensions/common/wasm/context.cc:1192] wasm log prompt_gateway: starting up arch filter in mode: prompt gateway mode               
[2024-11-01 07:34:30.907][158][debug][wasm] [source/extensions/common/wasm/context.cc:1192] wasm log prompt_gateway: starting up arch filter in mode: prompt gateway mode               
[2024-11-01 07:34:35.602][9][debug][wasm] [source/extensions/common/wasm/context.cc:1192] wasm log prompt_gateway: filter_context: on_http_call_response called with token_id: 4        
[2024-11-01 07:34:35.602][57][debug][wasm] [source/extensions/common/wasm/context.cc:1192] wasm log prompt_gateway: filter_context: on_http_call_response called with token_id: 8       
[2024-11-01 07:34:35.602][9][critical][wasm] [source/extensions/common/wasm/context.cc:1204] wasm log prompt_gateway: panicked at prompt_gateway/src/filter_context.rs:148:25:          
Error deserializing embedding response. body: "upstream connect error or disconnect/reset before headers. reset reason: connection timeout": Error("expected value", line: 1, column: 1)
[2024-11-01 07:34:35.602][141][debug][wasm] [source/extensions/common/wasm/context.cc:1192] wasm log prompt_gateway: filter_context: on_http_call_response called with token_id: 8      
[2024-11-01 07:34:35.602][57][critical][wasm] [source/extensions/common/wasm/context.cc:1204] wasm log prompt_gateway: panicked at prompt_gateway/src/filter_context.rs:148:25:         
Error deserializing embedding response. body: "upstream connect error or disconnect/reset before headers. reset reason: connection timeout": Error("expected value", line: 1, column: 1)
[2024-11-01 07:34:35.602][141][critical][wasm] [source/extensions/common/wasm/context.cc:1204] wasm log prompt_gateway: panicked at prompt_gateway/src/filter_context.rs:148:25:        
Error deserializing embedding response. body: "upstream connect error or disconnect/reset before headers. reset reason: connection timeout": Error("expected value", line: 1, column: 1)
[2024-11-01 07:34:35.603][9][error][wasm] [source/extensions/common/wasm/wasm_vm.cc:38] Function: proxy_on_http_call_response failed: Uncaught RuntimeError: unreachable                
Proxy-Wasm plugin in-VM backtrace:                                                                                                                                                      
  0:  0xd23a1 - __rust_start_panic                                                                                                                                                      
  1:  0xd2266 - rust_panic                                                                                                                                                              
  2:  0xd201c - std::panicking::rust_panic_with_hook::h50e657195af0239c                                                                                                                 
  3:  0xd1363 - std::panicking::begin_panic_handler::_$u7b$$u7b$closure$u7d$$u7d$::h0187e6969a85aab0                                                                                    
  4:  0xd12ca - std::sys_common::backtrace::__rust_end_short_backtrace::h575fb82445d56667                                                                                               
  5:  0xd1bb4 - rust_begin_unwind                                                                                                                                                       
  6:  0xd743f - core::panicking::panic_fmt::ha6764f2272b7fb95                                                                                                                           
  7:  0x7e0ba - _$LT$prompt_gateway..filter_context..FilterContext$u20$as$u20$proxy_wasm..traits..Context$GT$::on_http_call_response::hb27b0eacd5787919                                 
  8:  0xc5d4a - proxy_wasm::dispatcher::Dispatcher::on_http_call_response::h010c524b3251d0a7                                                                                            
  9:  0xcacd6 - proxy_on_http_call_response
